import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import '@/styles/globals.css'
import '@/styles/app.css'
import '@/styles/categoryCard.css'
import '@/styles/navBar.css'
import '@/styles/offcanvas.css'
import '@/styles/categoryModal.css'
import '@/styles/contact.css'
import { useEffect } from 'react';
import MachineVisionImage from '@/images/machine-vision.png'
import ValImage from '@/images/validation.png'
import MachineControlImage from '@/images/machine-control.png'
import LogoImage from '@/images/triton-technologies.png'
import CategoryCard from './components/categoryCard';
import NavBar from './components/navBar';

export default function App() {
  // Bootstrap uses some only client-side objects (window, document) to handle events. On the other hand, Next.js 
  // renders the app on both the server side and the client side. To avoid the mentioned errors, we have to make 
  //sure that the window and document objects only be used on the client side. That can be done with the useEffect hook
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap');
  }, [])

  return (
    <div className="app-main">
      <Head>
        <title>Triton Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar logo={LogoImage}/>
      <div className="summary">
      Triton Technologies brings a wealth of expertise to the table, honed over a decade of experience in machine control, vision systems, 
      and system qualification. Let us be your guide to overcoming production and automation challenges with ease.
      </div>
      <div className="category-cards">
        <div className="row">
          {/*  Machine Control, Machine Vision, Human Machine Interfaces, Robotics, Qualification and Validation */}
          <div className="col-sm">
            <CategoryCard image={MachineControlImage} title="Machine Control" modal={"#categoryModal1"}/>
          </div>
          <div className="col-sm">
            <CategoryCard image={MachineVisionImage} title="Machine Vision" modal={"#categoryModal2"}/>
          </div>
          <div className="col-sm">
          <CategoryCard image={ValImage} title="System Qualification" modal={"#categoryModal5"}/>
          </div>
        </div>
      </div >
      <div className="bottom-space"></div>
    </div >
  )
}
